name: Rust

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd
            bin: sync-clipboard
            name: sync-clipboard-FreeBSD-x86_64.tar.gz
            skip-tests: true
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            bin: sync-clipboard
            name: sync-clipboard-Linux-x86_64-musl.tar.gz
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            bin: sync-clipboard
            name: sync-clipboard-Linux-aarch64-musl.tar.gz
          - os-name: Linux-arm
            runs-on: ubuntu-24.04
            target: arm-unknown-linux-musleabi
            bin: sync-clipboard
            name: sync-clipboard-Linux-arm-musl.tar.gz
          - os-name: Linux-i686
            runs-on: ubuntu-24.04
            target: i686-unknown-linux-musl
            bin: sync-clipboard
            name: sync-clipboard-Linux-i686-musl.tar.gz
            skip-tests: true
          - os-name: Linux-powerpc
            runs-on: ubuntu-24.04
            target: powerpc-unknown-linux-gnu
            bin: sync-clipboard
            name: sync-clipboard-Linux-powerpc-gnu.tar.gz
            skip-tests: true
          - os-name: Linux-powerpc64
            runs-on: ubuntu-24.04
            target: powerpc64-unknown-linux-gnu
            bin: sync-clipboard
            name: sync-clipboard-Linux-powerpc64-gnu.tar.gz
            skip-tests: true
          - os-name: Linux-powerpc64le
            runs-on: ubuntu-24.04
            target: powerpc64le-unknown-linux-gnu
            bin: sync-clipboard
            name: sync-clipboard-Linux-powerpc64le.tar.gz
            skip-tests: true
          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
            bin: sync-clipboard
            name: sync-clipboard-Linux-riscv64gc-gnu.tar.gz
          - os-name: Linux-s390x
            runs-on: ubuntu-24.04
            target: s390x-unknown-linux-gnu
            bin: sync-clipboard
            name: sync-clipboard-Linux-s390x-gnu.tar.gz
            skip-tests: true
          - os-name: NetBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-netbsd
            bin: sync-clipboard
            name: sync-clipboard-NetBSD-x86_64.tar.gz
            skip-tests: true
          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            bin: sync-clipboard.exe
            name: sync-clipboard-Windows-aarch64.zip
            skip-tests: true
          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            bin: sync-clipboard.exe
            name: sync-clipboard-Windows-i686.zip
            skip-tests: true
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: sync-clipboard.exe
            name: sync-clipboard-Windows-x86_64.zip
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            bin: sync-clipboard
            name: sync-clipboard-Darwin-x86_64.tar.gz
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            bin: sync-clipboard
            name: sync-clipboard-Darwin-aarch64.tar.gz


    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: sync-clipboard
          target: ${{ matrix.platform.target }}
